spring.application.name=placement-portal

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/campus_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Keerthana@09}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}